### ISSUE TITLE
iOS 7.0 compatibility

### ISSUE THREAD

**Issue by SpacyRicochet** [xxxAIRINxxx/SwAlert#1]
Your documentation mentions that this library is compatible with iOS 7.0 and higher. However, the pod spec defines the compatibility to be iOS 8.0 or higher. 

Is the documentation out of date, or is the pod spec wrong?

**Comment by xxxAIRINxxx** [comment]
Hi.
Can't push cocoapods trunk...

```
 - ERROR | [iOS] Swift support uses dynamic frameworks and is therefore only supported on iOS > 8.
```
