### ISSUE TITLE
No alert is showing sometimes

### ISSUE THREAD

**Issue by ravifullestop** [xxxAIRINxxx/SwAlert#2]
There is weird issue sometimes stuck in below block of code

if AlertManager.sharedInstance.parentController.presentedViewController != nil {
            AlertManager.sharedInstance.alertQueue.append(self)
            return
        }

There is no alert either. Suddenly stops working everything

**Comment by xxxAIRINxxx** [comment]
Hi.
Sorry for the delay in my response...
I resolved it.

9bd6390a143898188f64b1b4714fc5f7d0a95032

Thanks!

**Comment by ravifullestop** [comment]
Not working still. Taking time to show an alert. Alert show when other controller pushed or something else.
