### ISSUE TITLE
Attempt to present UIAlertController  on  UIViewController which is already presenting UIAlertController

### ISSUE THREAD

**Issue by ravifullestop** [xxxAIRINxxx/SwAlert#3]
Attempt to present UIAlertController  on  UIViewController which is already presenting UIAlertController

**Comment by xxxAIRINxxx** [comment]
Hi.
Sorry for the delay in my response...
I resolved it.

9bd6390a143898188f64b1b4714fc5f7d0a95032

Thanks!
