### ISSUE TITLE
Have to make 'public' every class func to use in swift project

### ISSUE THREAD

**Issue by synergetica11** [xxxAIRINxxx/SwAlert#5]
For instance

 public class func showOneActionAlert(title: String, message: String, buttonTitle: String, completion: CompletionHandler?) {

Otherwise no way to compiler to see methods from pod project.
Although they are visible if I add without using pod.

**Comment by xxxAIRINxxx** [comment]
oops..

i resolved it.

d0be1b173e8d19802af880a7aa30df53d54ebfec

thanks!
